name: speed_guarana_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1



environment:
  sdk: ^3.10.3
  

# --- BLOCO DE DEPENDÊNCIAS UNIFICADO ---
dependencies:
  flutter:
    sdk: flutter

  # Ícones Padrão
  cupertino_icons: ^1.0.8

  # Gerenciamento de Estado (Essencial para a montagem do copo)
  provider: ^6.0.5
  
  # Navegação (Rotas limpas)
  go_router: ^12.0.0
  
  # Requisições HTTP (Conectar com Back-end)
  dio: ^5.3.0
  
  # Design & Fontes
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0 
  
  # Funcionalidades Específicas
  qr_flutter: ^4.1.0 
  mobile_scanner: ^3.2.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  